// import DOMPurify from "isomorphic-dompurify"; // runs on server too

export function formatStatePage(item) {
  const acf = item.acf || {};

  return {
    slug: item.slug,
    hero: {
      name: acf.state_name,
      image: acf.state_image,
    },

    makeindia: {
      heading: acf.section_title,
      sub: acf.sub_title,
      desc: DOMPurify.sanitize(acf.sub_paragraph || ""),
      para: DOMPurify.sanitize(acf.paragraph || ""),
      extra: DOMPurify.sanitize(acf.extra_paragraph || ""),
      amenities: (acf.amenities_list || []).map((a) => ({
        // strip tags like <br> but keep safe text
        title: DOMPurify.sanitize(a.amenities_title || "").replace(
          /<[^>]+>/g,
          ""
        ),
        image: a.amenities_image || null,
        alt: a.amenities_image_alt || "",
      })),
    },
    indicators: (acf.indicator_data || []).map((ind) => ({
      // sanitized but keep <sup>, %, etc. intact
      value: DOMPurify.sanitize(ind.indicator_no || "", {
        ALLOWED_TAGS: [
          "sup",
          "sub",
          "br",
          "span",
          "p",
          "div",
          "strong",
          "em",
          "b",
          "i",
          "u",
          "small",
          "big",
          "mark",
          "del",
          "ins",
          "code",
          "pre",
          "blockquote",
          "hr",
          "a",
          "ul",
          "ol",
          "li",
          "table",
          "thead",
          "tbody",
          "tr",
          "th",
          "td",
          "caption",
          "col",
          "colgroup",
          "dfn",
          "kbd",
          "samp",
          "var",
          "q",
          "cite",
          "abbr",
          "address",
          "bdi",
          "bdo",
          "wbr",
          "ruby",
          "rt",
          "rp",
        ],
      }),
      label: DOMPurify.sanitize(ind.indicator_description || ""),
    })),
    industrialLandscape: {
      title: acf.section_title1,
      // paragraph: DOMPurify.sanitize(acf.paragraph1 || ""),
      paragraph: acf.paragraph1 || "",
    },
    focusSectors: (acf.incentivised_list || []).map((s) =>
      DOMPurify.sanitize(s.list_text || "")
    ),
    parks: {
      title: acf.section_title_parks,
      stitle1: acf.state_park_title_1,
      stitle2: acf.state_park_title_2,
      paragraph: DOMPurify.sanitize(acf.paragraph_parks || "", {
        ALLOWED_TAGS: [
          "sup",
          "sub",
          "br",
          "span",
          "p",
          "div",
          "strong",
          "em",
          "b",
          "i",
          "u",
          "small",
          "big",
          "mark",
          "del",
          "ins",
          "code",
          "pre",
          "blockquote",
          "hr",
          "a",
          "ul",
          "ol",
          "li",
          "table",
          "thead",
          "tbody",
          "tr",
          "th",
          "td",
          "caption",
          "col",
          "colgroup",
          "dfn",
          "kbd",
          "samp",
          "var",
          "q",
          "cite",
          "abbr",
          "address",
          "bdi",
          "bdo",
          "wbr",
          "ruby",
          "rt",
          "rp",
        ],
        ALLOWED_ATTR: [],
      }),
    },

    faqs: (acf.faq_list || []).map((f) => ({
      no: f.faq_no,
      title: DOMPurify.sanitize(f.faq_title || ""),
      desc: DOMPurify.sanitize(f.faq_description || ""),
    })),
    regionSlider: (acf.region_slider || []).map((r) => ({
      name: r.state_name_region,
      image: r.state_image_region,
      url: r.state_url,
      alt: r.region_image_alt || "",
    })),
    meta: {
      title: acf.meta_title,
      description: acf.meta_description,
    },
  };
}
