// export const hotspotsData = {
//   1: [
//     {
//       id: "h5",
//       x: "50%",
//       y: "32%",
//       position: "right",
//       title: "Roof",
//       description: "Standing seam roof with <br/>sturdy bare galvalume sheets",
//       iwidth: 60,
//       fwidth: 240,
//     },
//     {
//       id: "h6",
//       x: "10%",
//       y: "42%",
//       position: "right",
//       title: "Building Height",
//       description: "12m at eaves",
//       iwidth: 120,
//       fwidth: 160,
//     },
//     {
//       id: "h2",
//       x: "87%",
//       y: "50%",
//       position: "left",
//       title: "Parking",
//       description:
//         "2 and 4-wheeler parking, <br/>truck parking designed for<br/>peak period load",
//       iwidth: 90,
//       fwidth: 240,
//     },
//     {
//       id: "h7",
//       x: "25%",
//       y: "55%",
//       position: "right",
//       title: "Building Structure",
//       description:
//         "Pre-engineered buildings with <br/>optimized column spacing",
//       iwidth: 140,
//       fwidth: 250,
//     },
//     {
//       id: "h8",
//       x: "50%",
//       y: "60%",
//       position: "right",
//       title: "Office Area",
//       description:
//         "Ground and bare-shell <br/>mezzanine floor <br/>on 2.5% of total area",
//       iwidth: 100,
//       fwidth: 190,
//     },
//     {
//       id: "h9",
//       x: "70%",
//       y: "60%",
//       position: "right",
//       title: "Truck Apron",
//       description: "16.5m concrete apron with <br/>12m wide roads",
//       iwidth: 100,
//       fwidth: 220,
//     },
//     {
//       id: "h10",
//       x: "85%",
//       y: "37%",
//       position: "left",
//       title: "Security",
//       description: "24*7 CCTV surveillance<br/>at main gate",
//       iwidth: 90,
//       fwidth: 220,
//     },
//   ],
//   2: [
//     {
//       id: "h11",
//       // Changed from "15%" → responsive clamp between 15% (≥1366) and 17% (<1366)
//       x: "25%",
//       y: "25%",
//       position: "right",
//       title: "Fire Protection",
//       description:
//         "Fire detection, alarms, fire escape<br/>doors, K160 and K80 sprinklers,<br/>external hydrants",
//       iwidth: 140,
//       fwidth: 260,
//     },
//     {
//       id: "h12",
//       x: "50%",
//       y: "10%",
//       position: "right",
//       title: "Efficient Lighting",
//       description:
//         "Skylights covering 3-5% of<br/>roof areas, LED light fixtures",
//       iwidth: 130,
//       fwidth: 240,
//     },
//     {
//       id: "h13",
//       x: "17%",
//       y: "87%",
//       position: "right",
//       title: "Wall",
//       description: "Pre-cast concrete walls/block<br/>walls up to 3.6 m height",
//       iwidth: 60,
//       fwidth: 240,
//     },
//     {
//       id: "h14",
//       x: "45%",
//       y: "94%",
//       position: "right",
//       title: "Floor",
//       description: "UDL 5T/sqm,<br/>FM2-compliant design",
//       iwidth: 60,
//       fwidth: 200,
//     },
//     {
//       id: "h15",
//       x: "60%",
//       y: "80%",
//       position: "right",
//       title: "Ventilation",
//       description:
//         "3-6 air changes, passive<br/>ventilation through louvers,<br/>and roof monitor",
//       iwidth: 100,
//       fwidth: 230,
//     },
//     {
//       id: "h16",
//       x: "95%",
//       y: "90%",
//       position: "left",
//       title: "Dock Area",
//       description: "Dock height 1.2m<br/>with rolling shutters,<br/>dock pits",
//       iwidth: 100,
//       fwidth: 200,
//     },
//   ],
// };

export const hotspotsData = {
  1: [
    {
      id: "h5",
      x: "48%",
      y: "30%",
      position: "right",
      title: "Roof",
      description: "Standing seam roof with <br/>sturdy bare galvalume sheets",
      iwidth: 60,
      fwidth: 240,
    },
    {
      id: "h6",
      x: "12%",
      y: "40%",
      position: "right",
      title: "Building Height",
      description: "12m at eaves",
      iwidth: 120,
      fwidth: 160,
    },
    {
      id: "h2",
      x: "85%",
      y: "48%",
      position: "left",
      title: "Parking",
      description:
        "2 and 4-wheeler parking, <br/>truck parking designed for<br/>peak period load",
      iwidth: 90,
      fwidth: 240,
    },
    {
      id: "h7",
      x: "23%",
      y: "53%",
      position: "right",
      title: "Building Structure",
      description:
        "Pre-engineered buildings with <br/>optimized column spacing",
      iwidth: 140,
      fwidth: 250,
    },
    {
      id: "h8",
      x: "48%",
      y: "58%",
      position: "right",
      title: "Office Area",
      description:
        "Ground and bare-shell <br/>mezzanine floor <br/>on 2.5% of total area",
      iwidth: 100,
      fwidth: 190,
    },
    {
      id: "h9",
      x: "68%",
      y: "58%",
      position: "right",
      title: "Truck Apron",
      description: "16.5m concrete apron with <br/>12m wide roads",
      iwidth: 100,
      fwidth: 220,
    },
    {
      id: "h10",
      x: "83%",
      y: "35%",
      position: "left",
      title: "Security",
      description: "24*7 CCTV surveillance<br/>at main gate",
      iwidth: 90,
      fwidth: 220,
    },
  ],
  2: [
    {
      id: "h11",
      x: "23%",
      y: "23%",
      position: "right",
      title: "Fire Protection",
      description:
        "Fire detection, alarms, fire escape<br/>doors, K160 and K80 sprinklers,<br/>external hydrants",
      iwidth: 140,
      fwidth: 260,
    },
    {
      id: "h12",
      x: "48%",
      y: "9%",
      position: "right",
      title: "Efficient Lighting",
      description:
        "Skylights covering 3-5% of<br/>roof areas, LED light fixtures",
      iwidth: 130,
      fwidth: 240,
    },
    {
      id: "h13",
      x: "15%",
      y: "85%",
      position: "right",
      title: "Wall",
      description: "Pre-cast concrete walls/block<br/>walls up to 3.6 m height",
      iwidth: 60,
      fwidth: 240,
    },
    {
      id: "h14",
      x: "43%",
      y: "92%",
      position: "right",
      title: "Floor",
      description: "UDL 5T/sqm,<br/>FM2-compliant design",
      iwidth: 60,
      fwidth: 200,
    },
    {
      id: "h15",
      x: "58%",
      y: "78%",
      position: "right",
      title: "Ventilation",
      description:
        "3-6 air changes, passive<br/>ventilation through louvers,<br/>and roof monitor",
      iwidth: 100,
      fwidth: 230,
    },
    {
      id: "h16",
      x: "93%",
      y: "88%",
      position: "left",
      title: "Dock Area",
      description: "Dock height 1.2m<br/>with rolling shutters,<br/>dock pits",
      iwidth: 100,
      fwidth: 200,
    },
  ],
};
